apiVersion: v1
data:
  api_pass: {{ .Values.api_pass | b64enc }}
  api_user: {{ .Values.api_user | b64enc }}
  db_host: {{ .Values.db_host | b64enc }}
  db_pass: {{ .Values.db_pass | b64enc }}
  db_port: {{ "5432" | b64enc }}
  db_user: {{ .Values.db_user | b64enc }}
  db_name: {{ .Values.db_name | b64enc }}
  frontend_origin_url: {{ .Values.frontend_origin_url | b64enc }}
kind: Secret
metadata:
  name: merch-api-creds
type: Opaque
