image:
  repository: jalgraves/beantown
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 3000

ingress:
  enabled: false

logLevel: tiny

nodeEnv: ""

kafka_bootstrap_server:
kafka_password:
kafka_username:
session_secret:
square_access_token_dev:
square_access_token_prod:
square_application_id_sandbox:
square_url:
