apiVersion: v1
data:
  kafka_bootstrap_server: {{ .Values.kafka_bootstrap_server | b64enc }}
  kafka_password: {{ .Values.kafka_password | b64enc }}
  kafka_username: {{ .Values.kafka_username | b64enc }}
  session_secret: {{ .Values.session_secret | b64enc }}
  square_access_token_dev: {{ .Values.square_access_token_dev | b64enc }}
  square_access_token_prod: {{ .Values.square_access_token_prod | b64enc }}
  square_application_id_sandbox: {{ .Values.square_application_id_sandbox | b64enc }}
  square_url: {{ .Values.square_url | b64enc }}
kind: Secret
metadata:
  name: beantown-creds
type: Opaque
