apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thehubpub
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /helm/thehubpub
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  source:
    path: helm/thehubpub/
    repoURL: git@github.com:beantownpub/thehubpub.git
    targetRevision: main
    helm:
      releaseName: thehubpub
      valueFiles:
        - values.yaml
      parameters:
        - name: env
          value: prod
        - name: regionCode
          value: use2
        - name: "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
          value: arn:aws:iam::112138771825:role/ProductionUse2TheHubPub
        - name: aws.region
          value: us-east-2
        - name: aws.secretName
          value: production-use2-thehubpub-creds
        - name: istio.enabled
          value: "true"
        - name: externalSecrets.enabled
          value: "true"
  project: services
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
