{{- if .Values.cilium.hubble.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hubble
spec:
  hosts:
  - "{{ .Values.cilium.hubble.hostname }}"

  gateways:
  - {{ .Release.Namespace }}/web-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - route:
    - destination:
        port:
          number: 80
        host: "hubble-ui.kube-system.svc.cluster.local"
{{- end }}
