{{- if .Values.externalSecrets.enabled -}}
# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: "{{ .Release.Namespace }}-use1"
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: us-east-1
#       auth:
#         secretRef:
#           accessKeyIDSecretRef:
#             name: external-secrets
#             key: AWS_ACCESS_KEY_ID
#           secretAccessKeySecretRef:
#             name: external-secrets
#             key: AWS_SECRET_ACCESS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "psql.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Release.Namespace }}-{{ .Values.regionCode }}"
    kind: SecretStore
  target:
    name: {{ include "psql.fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "{{ .Values.environment }}/{{ .Values.regionCode }}/{{ include "psql.fullname" . }}"
{{- end -}}
