{{- if .Values.pvc.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-database
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "psql.fullname" . }}
spec:
  storageClassName: aws-database
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end -}}
