---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "psql.fullname" . }}
spec:
  serviceName: {{ include "psql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      serviceAccountName: {{ include "psql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
          - name: PGDATA
            value: {{ .Values.pgDataDir }}
          - name: POSTGRES_USER
            value: wtf
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ADMIN_PASSWORD
                name: {{ include "psql.fullname" . }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: ADMIN_PASSWORD
                name: {{ include "psql.fullname" . }}
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                key: ADMIN_USERNAME
                name: {{ include "psql.fullname" . }}
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                key: DATABASE_PASSWORD
                name: {{ include "psql.fullname" . }}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DATABASE_USERNAME
                name: {{ include "psql.fullname" . }}
          - name: CONTACT_DB_NAME
            valueFrom:
              secretKeyRef:
                key: CONTACT_API_DB_NAME
                name: {{ include "psql.fullname" . }}
          - name: MENU_DB_NAME
            valueFrom:
              secretKeyRef:
                key: MENU_API_DB_NAME
                name: {{ include "psql.fullname" . }}
          - name: MERCH_DB_NAME
            valueFrom:
              secretKeyRef:
                key: MERCH_API_DB_NAME
                name: {{ include "psql.fullname" . }}
          - name: USERS_DB_NAME
            valueFrom:
              secretKeyRef:
                key: USERS_API_DB_NAME
                name: {{ include "psql.fullname" . }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: db-bootstrap
            mountPath: /docker-entrypoint-initdb.d/
          {{- if .Values.pvc.enabled }}
          - name: {{ include "psql.fullname" . }}
            mountPath: /var/lib/psqlql/data
          {{- end }}
      volumes:
      - name: db-bootstrap
        configMap:
          name: db-bootstrap
          items:
          - key: pg_user.sh
            path: init-user-db.sh
      {{- if .Values.pvc.enabled }}
      - name: {{ include "psql.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "psql.fullname" . }}
      {{- end -}}
