{{- if eq .Values.global.env "dev" }}
apiVersion: v1
data:
  aws_access_key_id: {{ .Values.aws_access_key_id | b64enc }}
  aws_default_region: {{ .Values.aws_default_region | b64enc }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key | b64enc }}
kind: Secret
metadata:
  name: contact-api-creds
type: Opaque
{{- end }}

