apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-external-dns
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /aws-external-dns
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: aws-external-dns/
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: main
    helm:
      releaseName: aws-external-dns
      parameters:
        - name: "aws-external-dns.domainFilters[0]"
          value: "use2.production.aws.beantownpub.com"
      valueFiles:
        - values-production-use2.yaml
  project: default
  syncPolicy: {}
