apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /aws-load-balancer-controller
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: aws-load-balancer-controller/
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: main
    helm:
      releaseName: aws-load-balancer-controller
      parameters:
        - name: "aws-load-balancer-controller.clusterName"
          value: "production-use2"
  project: default
  syncPolicy:
    automated:
      selfHeal: true
