apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /external-secrets
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    path: external-secrets/
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: main
    helm:
      releaseName: external-secrets
      parameters:
        - name: aws.region
          value: us-east-2
        - name: env
          value: production
        - name: external-secrets.roleArn
          value: arn:aws:iam::112138771825:role/ProductionUse2ExternalSecrets
        - name: "external-secrets.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
          value: arn:aws:iam::112138771825:role/ProductionUse2ExternalSecrets
  project: infrastructure
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
