apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /istio
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  source:
    path: istio/
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: main
    helm:
      releaseName: istio
      valueFiles:
        - values-production-use2.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
