apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psql
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /psql
spec:
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  source:
    path: psql/
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: main
    helm:
      releaseName: psql
      parameters:
        - name: contactDbName
          value: contact_api
        - name: contentDbName
          value: content_api
        - name: menuDbName
          value: menu_api
        - name: merchDbName
          value: merch_api
        - name: usersDbName
          value: users_api
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m0s
