{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
labels:
  type: local
spec:
  storageClassName: aws
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
{{- end -}}
