apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: web-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.domain }}"
    - "*.{{ .Values.domain }}"
    - "*.{{ .Values.global.env }}.{{ .Values.domain }}"
  {{- range .Values.additionalHosts }}
    - {{ .| quote }}
  {{- end }}
