apiVersion: v2
name: istio
description: Deploy Istio
version: 0.1.10

dependencies:
  - name: gateway
    version: 1.23.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.23.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: base
    version: 1.23.2
    repository: https://istio-release.storage.googleapis.com/charts
