albCertificateArn:
argoCd:
  enabled: false
certArns:
  - arn:aws:acm:us-east-1:826438047975:certificate/387a92d7-1e44-4f04-8ebd-ef7eb3fbf7be

cilium:
  hubble:
    enabled: true
    hostname: "hubble.development.use1.jalgraves.com"

environment: development
org: jalgraves
regionCode: use1
sslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

ingress:
  albPrivate:
    enabled: false
    accessLogs:
      enabled: false
    externalDns:
      hostnames: []
  albPublic:
    enabled: true
    accessLogs:
      enabled: false
    externalDns:
      hostnames:
        - "*.development.use1.jalgraves.com"
  gatewayDomains:
    - development.use1.jalgraves.com
    - "*.development.use1.jalgraves.com"
  serviceName: istio
gateway:
  replicaCount: 1
  # nodeSelector:
  #   control-plane-node: init
  service:
    type: NodePort
    annotations: {}

  tolerations: []

istiod:
  global:
    defaultPodDisruptionBudget:
      enabled: false
    logAsJson: true
    proxy:
      excludeOutboundPorts: "8125,8126,8200"
  pilot:
    # nodeSelector:
    #   control-plane-node: init
    env:
      # If enabled, Pilot will send only clusters that referenced in gateway virtual services attached to gateway
      # https://istio.io/latest/docs/reference/commands/pilot-agent/
      PILOT_FILTER_GATEWAY_CLUSTER_CONFIG: true
    resources:
      requests:
        memory: 1Gi
    tolerations: []

proxyV2:
  enabled: true
