# albCertificateArn
# This is the AWS ACM certificate arn for *.use1.hqo-production.com
# The ALB is only reachable on the private network and used as
# gateway to connect to prometheus and kiali when connected you're
# on the tailscale VPN
# The arn is located in the outputs from the terraform workspace production-aws-eks-use1
# The arns are located in the outputs from the terraform workspace production-aws-route53-use1
# https://app.terraform.io/app/jalgraves/workspaces/production-aws-route53-use2

certArns:
  - arn:aws:acm:us-east-1:104215655692:certificate/6100cffa-4c89-4ba5-818e-a4ce0a7092cf,
  - arn:aws:acm:us-east-1:104215655692:certificate/99dfea65-1c9e-4754-8942-190a7cc5f3a2

environment: production

gateway:
  autoscaling:
    minReplicas: 1
  replicaCount: 1

ingress:
  albPrivate:
    enabled: false
    accessLogs:
      enabled: true
    externalDns:
      hostnames: []
  albPublic:
    enabled: true
    accessLogs:
      enabled: true
    externalDns:
      hostnames:
      # hostnames that aws-external-dns will create DNS records for in route53 to
      # point to the public Application Load Balancer
        - "*.use1.production.aws.beantownpub.com"
  gatewayDomains:
    - "*.use1.production.aws.beantownpub.com"

istiod:
  pilot:
    autoscaleMin: 2
    replicaCount: 2
  # To disable access logs:
  # meshConfig: {}
  meshConfig: {}
    # accessLogFile: /dev/stdout
    # accessLogEncoding: JSON

regionCode: use1
sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
