albCertificateArn:
argoCd:
  enabled: false
certArns:
cilium:
  hubble:
    enabled: true

environment: production
org: beantownpub
regionCode: use2
sslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

ingress:
  albPrivate:
    enabled: false
    accessLogs:
      enabled: false
    externalDns:
      hostnames: []
  albPublic:
    enabled: true
    accessLogs:
      enabled: false
    externalDns:
      hostnames:
        - "*.production.use2.aws.beantownpub.com"
  gatewayDomains:
    - "*.beantownpub.com"
    - "*.thehubpub.com"
    - "*.drdavisicecream.com"
    - "*.wavelengths-brookline.com"
    - "*.jalgraves.com"
  serviceName: istio
gateway:
  replicaCount: 1
  nodeSelector:
    role: worker
  service:
    type: NodePort
    annotations: {}

  tolerations: []

istiod:
  global:
    defaultPodDisruptionBudget:
      enabled: false
    logAsJson: true
    proxy:
      excludeOutboundPorts: "8125,8126,8200"
  pilot:
    nodeSelector:
      role: worker
    env:
      # If enabled, Pilot will send only clusters that referenced in gateway virtual services attached to gateway
      # https://istio.io/latest/docs/reference/commands/pilot-agent/
      PILOT_FILTER_GATEWAY_CLUSTER_CONFIG: true
    resources:
      requests:
        memory: 1Gi
    tolerations: []

proxyV2:
  enabled: true
