albCertificateArn:
certArns:
environment:
regionCode:
sslPolicy:

ingress:
  albPrivate:
    enabled: true
    accessLogs:
      enabled: true
    externalDns:
      hostnames: []
  albPublic:
    enabled: true
    accessLogs:
      enabled: true
    externalDns:
      hostnames: []
  gatewayDomains: []
gateway:
  service:
    type: NodePort
    annotations: {}

  tolerations: []

istiod:
  global:
    defaultPodDisruptionBudget:
      enabled: false
    logAsJson: true
    proxy:
      excludeOutboundPorts: "8125,8126,8200"
  pilot:
    env:
      # If enabled, Pilot will send only clusters that referenced in gateway virtual services attached to gateway
      # https://istio.io/latest/docs/reference/commands/pilot-agent/
      PILOT_FILTER_GATEWAY_CLUSTER_CONFIG: true
    resources:
      requests:
        memory: 1Gi
    tolerations: []

proxyV2:
  enabled: true
