albCertificateArn:
argoCd:
  enabled: false
certArns:
  # "beantownpub-use1"
  - "arn:aws:acm:us-east-1:112138771825:certificate/6f4f262d-9056-4fd0-8bf2-3a0bd9cad42c"
  # "drdavisicecream-use1"
  - "arn:aws:acm:us-east-1:112138771825:certificate/a873ee25-0dce-48bb-b60e-0a19c8953f04"
  # "production-use1"
  - "arn:aws:acm:us-east-1:112138771825:certificate/adb4dc1c-f96e-4a3c-b72d-838f7a9aa1f5"
  # "thehubpub-use1"
  - "arn:aws:acm:us-east-1:112138771825:certificate/50b358d1-c996-460f-9025-855a9e95969e"
  # "wavelengths-brookline-use1"
  - "arn:aws:acm:us-east-1:112138771825:certificate/72cf4544-fb1c-443c-b865-9846ea0e9405"
cilium:
  hubble:
    enabled: false
    hostname: "hubble.production.use1.aws.beantownpub.com"

environment: production
org: beantownpub
regionCode: use1
sslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06

ingress:
  albPrivate:
    enabled: false
    accessLogs:
      enabled: false
    externalDns:
      hostnames: []
  albPublic:
    enabled: true
    accessLogs:
      enabled: false
    externalDns:
      hostnames:
        - "*.production.use1.aws.beantownpub.com"
  gatewayDomains:
    - beantownpub.com
    - "*.beantownpub.com"
    - thehubpub.com
    - "*.thehubpub.com"
    - drdavisicecream.com
    - "*.drdavisicecream.com"
    - wavelengths-brookline.com
    - "*.wavelengths-brookline.com"
    - jalgraves.com
    - "*.jalgraves.com"
    - oneflawedwage.com
    - "*.oneflawedwage.com"
  serviceName: istio
gateway:
  replicaCount: 1
  nodeSelector:
    role: istio
  service:
    type: NodePort
    annotations: {}

  tolerations: []

istiod:
  global:
    defaultPodDisruptionBudget:
      enabled: false
    logAsJson: true
    proxy:
      excludeOutboundPorts: "8125,8126,8200"
      resources:
        requests:
          cpu: 25m
  pilot:
    nodeSelector:
      role: istio
    env:
      # If enabled, Pilot will send only clusters that referenced in gateway virtual services attached to gateway
      # https://istio.io/latest/docs/reference/commands/pilot-agent/
      PILOT_FILTER_GATEWAY_CLUSTER_CONFIG: true
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
    tolerations: []

proxyV2:
  enabled: true
