kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: automation-rw-role
rules:
- apiGroups: ["", "batch", "extensions", "apps", "networking.istio.io"]
  resources: ["*"]
  verbs: ["*"]
