# This application is so that argocd can manage itself after initial deployment
{{- if .Values.createApplications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '1'
    helm.sh/hook-delete-policy: hook-failed
    argocd.argoproj.io/manifest-generate-paths: /argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argo-cd/
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: master
    helm:
          releaseName: argocd
  project: default
  syncPolicy: {}
    # automated:
    #   selfHeal: true
{{- end }}
