{{- if .Values.createApplications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-apps
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '1'
    helm.sh/hook-delete-policy: hook-failed
    argocd.argoproj.io/manifest-generate-paths: /argo-cd/apps/services
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argo-cd/apps/services
    repoURL: git@github.com:beantownpub/helm.git
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy: {}
{{- end }}
