apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
  labels:
    karpenter.sh/provisioner-name: default-provisioner
spec:
  instanceProfile: {{ .Values.aws.instanceProfile }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 10Gi
        volumeType: gp3
        iops: 3000
        encrypted: true
        deleteOnTermination: true
        throughput: 750
  subnetSelector:
    Name: "{{ .Values.clusterName }}-private*"
  securityGroupSelector:
    karpenter.sh/discovery/{{ .Values.clusterName }}: {{ .Values.clusterName }}
  tags:
    karpenter.sh/discovery/{{ .Values.clusterName }}: {{ .Values.clusterName }}
    Name: "{{ .Values.clusterName }}-k8s-worker"
    Provisioner: karpenter
  userData: |
    #!/bin/bash
    mkdir -p /home/ec2-user/.ssh/
    touch /home/ec2-user/.ssh/authorized_keys
    echo {{ .Values.aws.sshPublicKey }} >> /home/ec2-user/.ssh/authorized_keys
    chmod -R go-w ~ec2-user/.ssh/authorized_keys
    chown -R ec2-user ~ec2-user/.ssh
