apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-provisioner
spec:
  limits:
    resources:
      cpu: 1k
  providerRef:
    name: default
  labels:
    role: istio
  requirements:
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  - key: kubernetes.io/os
    operator: In
    values:
    - linux
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
    - spot
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values:
    - t3
    - t3a
  - key: topology.kubernetes.io/zone
    operator: In
    values: {{- toYaml .Values.aws.availabilityZones | nindent 8 }}
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values:
    - small
    - medium
    - large
  ttlSecondsAfterEmpty: 30
