apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
  labels:
    karpenter.sh/provisioner-name: default-provisioner
spec:
  instanceProfile: {{ .Values.aws.instanceProfile }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 10Gi
        volumeType: gp3
        iops: 3000
        encrypted: true
        deleteOnTermination: true
        throughput: 750
  subnetSelector:
    Name: "{{ .Values.clusterName }}-private*"
  securityGroupSelector:
    karpenter.sh/discovery/{{ .Values.clusterName }}: {{ .Values.clusterName }}
  tags:
    karpenter.sh/discovery/{{ .Values.clusterName }}: {{ .Values.clusterName }}
    Name: "{{ .Values.clusterName }}-default-node-template"
    Provisioner: karpenter
