apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-provisioner
spec:
  limits:
    resources:
      cpu: 1k
  providerRef:
    name: default
  labels:
    role: {{ .Values.defaultRole }}
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
        - spot
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: {{- toYaml .Values.aws.instanceTypes | nindent 8 }}
    - key: topology.kubernetes.io/zone
      operator: In
      values: {{- toYaml .Values.aws.availabilityZones | nindent 8 }}
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: {{- toYaml .Values.aws.instanceSizes | nindent 8 }}
  {{- if not .Values.consolidation.enabled }}
  ttlSecondsAfterEmpty: 30
  {{- end }}
  consolidation:
    enabled: {{ .Values.consolidation.enabled }}
  kubeletConfiguration:
    clusterDNS: ["10.96.0.10"]
    maxPods: {{ .Values.kubeletConfiguration.maxPods }}
  startupTaints:
    - key: node.cilium.io/agent-not-ready
      value: "true"
      effect: NoExecute
